[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
quota_vault = "94x5RJgCv2qvkyAFwDP3sdrxHq32WEaTi4dT22BrcgX1"

[provider]
cluster = "devnet"
wallet = "~/quota-api-signer.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
